### ISSUE TITLE
mod automatically grey itself out in repentance

### ISSUE THREAD

**Issue by pityhero233** [wofsauge/External-Item-Descriptions#150]
I was subscribed to this mod on steam workshop with repentance dlc, things were good for a few weeks, but yesterday I found out that item descriptions were no longer visible. I looked inside Mods tab, tried to disable and reenable the mod with Enter key. However, each time I enable the mod and press Esc to quit to main menu, then come back, the mod was greyed out again.
![image](https://user-images.githubusercontent.com/24752033/131803890-b2410eb0-75e3-4d9a-9425-86af60bb91ed.png)

**Comment by wofsauge** [comment]
Its impossible for mods to disable or enable themself. Therefore, this is not a problem caused by this mod but by your game. 
Also, since the mod names contain the steam id numbers inside their name, which they normally not do if installed via the steam workshop, it seems like either of the next things:

1. You deleted the metadata.xml file from the mods for some reason
2. You installed the mods manually
3. You might be on a different patch of the game. Always use the most up to date. (1.0.6j is the current one i think)

**Comment by pityhero233** [comment]
> Its impossible for mods to disable or enable themself. Therefore, this is not a problem caused by this mod but by your game.
> Also, since the mod names contain the steam id numbers inside their name, which they normally not do if installed via the steam workshop, it seems like either of the next things:
> 
>     1. You deleted the metadata.xml file from the mods for some reason
> 
>     2. You installed the mods manually
> 
>     3. You might be on a different patch of the game. Always use the most up to date. (1.0.6j is the current one i think)

I see. But pretty sure I didn't do all above. I installed mods solely from steam workshop, and didn't apply any patch to the game. To be double sure, I manually removed everything under ~/.local/share/steam/steamapps/Isaac/mods, and reinstalled the game and workshop contents. But the error persists.
If this is not the appropriate place to ask, may I know where can I seek help from then? Thanks!

**Comment by wofsauge** [comment]
Since you seem to use Linux instead of windows, the source of the inteference might be caused by it. In order to disable mods, the game writes a "disable.it" file into the mod folder. it might be that your system doesnt allow a program to delete this file, therefore the mod will turn disabled again. 

but this is just a guess, since i dont have Linux and have no idea how that stuff works there.

You might want to visit the official Binding of isaac Discord Server https://discord.gg/isaac   and / or the modding of isaac server https://discord.gg/yUZTqv5J for additional help

**Comment by pityhero233** [comment]
Thanks for the instructions. I reached to discord server, but the devs there didn't figure it out either. 
Since repentence does not have official support for Linux, I guess maybe it's some weird bug of proton experimental ...
Anyways, I'll be closing the issue then. Thanks!
