### ISSUE TITLE
File casing causing script to exit

### ISSUE THREAD

**Issue by MitchellHansen** [wofsauge/External-Item-Descriptions#206]
Going to play Binding of Isaac tonight, but noticed the mod quit working. Console shows a file not found error for :

`binding of isaac afterbirth+ mods/external item descriptions_836319872/eid_xmlData.lua`

It appears like it was introduced in this change :

https://github.com/wofsauge/External-Item-Descriptions/commit/3ecaaaca8beefd7a5ba8f0c5f90c69f4f33d3776

Simply changing the casing to `require("eid_xmldata")` fixed the problem for me. I don't know why my install has the lower cased versions of the filenames (`eid_xmldata.lua`, `eid_bagofcrafting.lua`, etc.), I see that it is camelCase in this repo. But, many people on the steam discussion page are having the same issue

**Comment by wofsauge** [comment]
Hey. Thanks for the report.
I made the files and require calls all lowercase now.

Since I'm not able to go on the pc in the next few days, do you might wanna try out for me, if these changes fixed the issue for you?
Simply download this repo, and replace the currently installed mod files with the ones you downloaded.
