### ISSUE TITLE
Add info about item in Bag of Crafting as T.Cain

### ISSUE THREAD

**Issue by Rafii2198** [wofsauge/External-Item-Descriptions#210]
So when you play as Tainted Cain you can't get items unless in Death Certificate area and story items. That means EID does not need to show items descriptions of ones near him as he can't get them anyway, instead it should show description of item in the Bag of Crafting as it is the only way he can acquire items. 
When playing as anyone else then you can't see content and result of Bag of Crafting and the item you craft will be dropped on the ground meaning EID does not need to do anything special for everyone else.

(Also my opinion about reverse engineering crafting formula)
If you want to put that feature in the mod I suggest to make it as an add-on for the base mod or make it disabled by default. The whole idea for Tainted Cain is to memories, take notes etc. for crafting formulas during that specific run. If a mod would show what to get to craft specific item then I would consider it as cheating because it is against the design. (Again it is just my opinion)

**Comment by Buurazu** [comment]
Non-TCain Bag of Crafting still uses the same recipe formula so displaying the same crafting info is still very useful for them, but yes I hate how you can never get the bag info off the screen, especially as non-TCain

I'll be adding a hotkey to toggle the crafting display on/off very soon, so that you can still see item/card/pill info when you have 8+ ingredients on the floor. I've also considered some kind of "automatic" mode, especially for non-TCain, where being near a describable item, the item takes precedence; although that could be messy with cards/pills that you're moving to to yoink for the bag (Maybe only non-baggable items take precedence), and real messy if you've gone infinite with pickups, although at that point you can't pick and choose recipes anyway... It could be worth being an option still.

I'm also working on a "simplified mode" that gives item pool percentages and component quality info instead of exact recipes, but it wouldn't be the default; the whole point of EID is to put in-game what you'd normally have to use external websites for, and people certainly use external websites for crafting! When I heard about the Bag of Crafting and used it, EID displayed exactly what I expected and I'm loving improving the thoroughness of its recipe list.

Not sure how to approach "display description of item ready to be crafted", aside from yet another hotkey, because it can't be an automatic thing; you're gonna want to keep looking at the recipe list most of the time you have 8 in the bag if you're familiar with the items or going towards a specific recipe still. But it is a good idea, as I've certainly had to look up info about items I'm not quite familiar with while crafting! I don't like all these hotkeys but I can't see a better way to approach the user choosing between normal mode, recipe list mode, and bag item mode...

**Comment by Buurazu** [comment]
I added a Preview Only display mode now for those that don't want any Bag of Crafting interaction, except for item descriptions with a full bag

**Comment by wofsauge** [comment]
Feature was implemented and is now mapped to F4 on default
