### ISSUE TITLE
Mod fails to start, error in line 11 of main.lua

### ISSUE THREAD

**Issue by Bionite** [wofsauge/External-Item-Descriptions#215]
Hello, been trying to get to run the mod as it should for a few days now but to no avail. I've tried things such as renaming the folder, making a folder in /data/, deleting metadata.xml. I'm attaching a screenshot of game launch message in debug console and when I try to run the mod via luamod command.
![image](https://user-images.githubusercontent.com/44941986/142626731-bf5f9a3e-e50c-4e67-b953-78a8885f4c4f.png)

**Comment by Buurazu** [comment]
main.lua Line 83 is where it loads eid_bagofcrafting, which just got switched to all lowercase file name, so I would try just redownloading the mod from the repo https://github.com/wofsauge/External-Item-Descriptions/archive/refs/heads/master.zip and making sure eid_xmldata and eid_bagofcrafting are all lowercase file names after replacing everything

**Comment by JasonHalvorson** [comment]
@Bionite do you have any mods active that could be changing item names/pickup text? I was getting this same error when I tried to use EID along with the [Yankee with no BRIMstone Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2395538481).

I had no issue running both of these mods before the latest Repentance update, so something in the update must have broken things.

**Comment by Buurazu** [comment]
Ah, thank you, installing that also makes this error. So, it's not related to main.lua:83, it's just that during bag of crafting setup, it accesses items.xml.

Yankee with no BRIMstone contains the entirety of items.xml, which is an INCREDIBLY poor idea. You're supposed to modify or add on to items.xml, not replace it.
The newest update added 3 new items. Brim's items.xml does not contain the new items (glass eye, stye, mom's ring). That means they can't spawn in any capacity. And it means that for the Bag of Crafting, which uses exported data from the game's actual items.xml, that it makes array out of bounds access errors happen immediately.

I'll get a fix in that won't flat out crash EID, as aside from my recent Bag of Crafting changes, I don't think EID would try to access these new item's data (since they never spawn!). But I must stress that you need to uninstall that, and any other mods that have a massive resources/items.xml file, or you literally can't see the new items, and might not even have the newest versions of items like C Section.

**Comment by JasonHalvorson** [comment]
I see, including a replacement items.xml instead of making modifications to it definitely seems like poor practice.

Hopefully @Bionite's issue is just due to a similar mod. Thanks for your insight!

**Comment by Buurazu** [comment]
Finding out more about this issue, I learned that outdated mods like that are also the cause of people crashing upon entering the Knife Piece 2 area, so I'm adding a warning like the Achievements Disabled warning if the mod detects less items in existence than it thinks there should be.

**Comment by Bionite** [comment]
@JasonHalvorson @Buurazu After removing every other mod that I was using and redownloading the mod, the only thing that happened is that main.lua:83 error got removed but eid_api.lua:439 still stays. 

![image](https://user-images.githubusercontent.com/44941986/142700078-63961e4c-bde2-47d6-93f3-964eb61cded8.png)

Also should mention that I see the mod in the mods tab in game. Even though it's enabled the item descriptions still do not show at all. Also tried clicking F2. A lot.

**Comment by Buurazu** [comment]
I've got a lot of changes not yet pushed, I'd like you to download this WIP build and see what happens: https://github.com/Buurazu/External-Item-Descriptions/archive/refs/heads/MoreBagStuff2.zip
Also make sure your game is updated and that you start a new run rather than continuing a run that had outdated mods installed

**Comment by Bionite** [comment]
@Buurazu Great news! After downloading the WIP build of the mod, it works perfectly. Thank you all so much and 'till another day, goodbye.

Enjoy the rest of your lives. :)
