### ISSUE TITLE
Pills not showing the right pill name

### ISSUE THREAD

**Issue by Neozaelks** [wofsauge/External-Item-Descriptions#228]
While using EID and "scanning" a pill on the ground, EID wrongly labels the pill, but shows the right pill effect.

example as Magladene
![isaac-ng_Mr7rNvhTRp](https://user-images.githubusercontent.com/44670682/142924331-72abac06-c71a-4f7d-902c-996ac5b078d3.png)

**Comment by Buurazu** [comment]
Looks like a result of the recent game update that made all the names something like "#FULL_HEALTH_NAME" instead of "Full Health" (for future localization ease), combined with copying the name display code from the other item types
All I have to do is change SubType to adjustedSubtype here: https://github.com/wofsauge/External-Item-Descriptions/blob/0cec04ba584e2719a3eb7cd61c9e0f5b533726d3/eid_api.lua#L451
Thanks for the report, I only use the default en_us and this wasn't an issue there
