### ISSUE TITLE
implement warning for deprecated Repentance Version users

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/External-Item-Descriptions#241]
this should warn people, if they are not on the most up-to-date version of the game. Detection can be done using new functions like "Options" or "HUD"

**Comment by Buurazu** [comment]
I'm working on this, and a few other suggestions / confusions i've seen in the steam comments, over the next couple days

This is what I have for warning text (they all use the Achievement Warning codeblock, so I'll rename that option in the config menu to something like "Start of Run Warnings:"

`EID.descriptions["en_us"].OldGameVersionWarningText = "Your version of Repentance is not up-to-date!#Only the newest version of Repentance is officially supported#(This warning can be disabled in the config)"`

`EID.descriptions["en_us"].ModdedRecipesWarningText = "Modded items are likely to make the crafting recipe calculation inaccurate!#Use the No Recipes display mode or turn off the Bag of Crafting display if your recipes are incorrect#(This warning can be disabled in the config)"`

It seemed like people annoyed by the warnings always ask if they can turn them off so I added that config bit

And I believe modded items only break crafting if they modify the item pools the bag pulls from (Treasure/Boss/Shop/Angel/Devil/Secret/etc) so if, say, a character mod adds an item that's only usable by that character and not in any pools, recipes should be fine, so that one definitely has a case where you'd want to disable the warning

**Comment by wofsauge** [comment]
Feature was implemented by @Buurazu now. Thanks :)
