### ISSUE TITLE
Bag of Crafting "Hide" indicates the keyboard key

### ISSUE THREAD

**Issue by Xantown7** [wofsauge/External-Item-Descriptions#304]
Hello!

![image](https://user-images.githubusercontent.com/21340420/149357034-4e88b138-cad9-4eb7-8cf5-19b313281824.png)

![image](https://user-images.githubusercontent.com/21340420/149356862-96339a7b-a0b5-45c4-bc53-f1173e645746.png)

As you can see, it displays "Hide : F3" instead of displaying the controller icon (RT in my case):

![image](https://user-images.githubusercontent.com/21340420/149357239-80e968c8-268f-4c7a-ad30-f435d43048cf.png)

That's not very important and just visual but I figured I could report it anyway

**Comment by Buurazu** [comment]
I didn't think of using the controller icons, that's a good idea and should save space.
And since there's no controller hotkeys by default, "Hide: F3, Preview: F4" will still be the default (it fits in one line so it looks nice)
I'll work on a change so that it can show only keyboard, only controller, or both, depending on what you have defined (and hopefully two controller icons will also fit on one line)

**Comment by Buurazu** [comment]
![image](https://user-images.githubusercontent.com/2997591/149588815-c10d1099-db6d-4298-b280-4448ed461dad.png)
Yay, one line! This can be closed now
