### ISSUE TITLE
Show next Donation Reward for Donation Machine and Greed Machine (similiar to next Sacrifice Room payout)

### ISSUE THREAD

**Issue by ghost** [wofsauge/External-Item-Descriptions#394]
i dunno but this might be useful

![image](https://user-images.githubusercontent.com/52797647/156063230-3b74afc2-9fa0-4767-a585-2b47094c0305.png)
![image](https://user-images.githubusercontent.com/52797647/156063488-0b26d518-035f-4070-814f-1bca32c8e4ac.png)
(for greed machine the same thing above but just different stuff)

**Comment by wofsauge** [comment]
For the Donation machine, this would be possible i think because we can determine if the stop watch (reward for 999 coins) is unlocked or not. it its not unlocked we know that the player is still on their first "fill" and therefore we can show the next reward.

For the Greed Donation Machine though, we cant determine if it is the first fill or not, because all the final unlocks are gameplay mechanics. we can only read unlock states from items and trinkets right now. the final unlock is Keeper tough, so no way of knowing.

**Comment by Buurazu** [comment]
There doesn't appear to be any way for Lua mods to know how many coins are inside a donation machine, in addition to it being difficult to determine if any items will be unlocked.
It could be part of the item collection page stuff that requires reading the save file.

**Comment by wofsauge** [comment]
Feature was added now with commit [4400ac7](https://github.com/wofsauge/External-Item-Descriptions/commit/4400ac72710c76d3195eaf24d010abeef9e6001e).
It requires Repentogon to work properly
