### ISSUE TITLE
Display Sanguine Bond reward chances when inside a devil room

### ISSUE THREAD

**Issue by biobak64** [wofsauge/External-Item-Descriptions#465]
Would be better to show the rewards and percentages inside the room rather than before picking up the item

**Comment by Buurazu** [comment]
Because the spikes are a grid entity, we don't have a fast way to check it for proximity. The best I can do is add the desc like we do for sacrifice rooms, but that's a bit awkward since devil rooms almost always have other items whose descs will take priority...

I think this might be better for when we finally add the "item reminders when holding Map" feature, that will also have things like Pandora's Box's current payout, Teleport 2.0's next destination, and also cheaty things like what D1 will dupe or if crooked penny will payout and such.

**Comment by wofsauge** [comment]
This is now implemented with the "Item Reminder" feature
