### ISSUE TITLE
Context-dependent description additions

### ISSUE THREAD

**Issue by biobak64** [wofsauge/External-Item-Descriptions#484]
Would help with some of the issues mentioned in [476](https://github.com/wofsauge/External-Item-Descriptions/issues/476#issue-1266708414).

Just like Book of Belial/Virtues or Tarot Cloth, i think there should be more context-dependent descriptions for individual characters (health-related items as (T)Keeper, synergies as (T)Azazel and T Forgotten, etc.) and Greed mode (some items straight up do not work in greed mode).

Might even be cool to add these for specific item interactions, like Black Candle cancelling the curses from Cursed Eye and Cursed penny. That bit would only show up if you already have one of the items.

Right now these interactions are displayed regardless of character or mode, cluttering the descriptions and possibly spoiling unlocks.

**Comment by Buurazu** [comment]
I do have a plan for this although I have to figure out how best to implement it, especially with multi-characters (like including both normal and tainted keeper under one var check)
For localization purposes, and keeping the relevant info together (rather than some separate table at the bottom of the file) I'm thinking they'd be a part of the localization files' table of text. Example:
`{"15", "XIV - Temperance", "{{DonationMachine}} Spawns a Blood Donation Machine", ["IsGreedMode"] = "{{GreedMode}} Spawns a Devil Beggar in Greed Mode"},`
Then there will be code for checking that we're in greed mode and append that text. There will definitely be another function usable in the localization like ["HasCollectible###"], so that any collectible could be checked

**Comment by Buurazu** [comment]
Part of it is that most of the text that would be separated with this, is already in the descriptions already. So it seems good to still keep that text close to each other.
And I don't think it'd be viable to have a "GreedText" table and a "Keeper" table and a "NoRedHP" table and such, because then all of them would have to get checked to check if they contain the ID we're printing. The heirarchy for programming it has to go entity ID -> function names to test IMO.
Perhaps having just one per line will be good for localizing it? Easier to read than a multiline string like it is now, even? So like
`{"15", "XIV - Temperance", "{{DonationMachine}} Spawns a Blood Donation Machine",
["IsGreedMode"] = "{{GreedMode}} Spawns a Devil Beggar in Greed Mode"},`

**Comment by wofsauge** [comment]
Feature was added using the Conditional modifier feature
