### ISSUE TITLE
Update Isaac Repentance

### ISSUE THREAD

**Issue by vazquezca** [wofsauge/External-Item-Descriptions#53]
Hi! I'm just an isaac player and I really love your mod. I'm here to ask you if you'll update as soon as possible the new items from the new expansion coming.

**Comment by wofsauge** [comment]
hi, yes i will try to update the mod as soon as possible. I aim at making it work for repentence on day 1 of its release.
But i cant promise fully working descriptions for the new items right away since the community has to find out what all of them do, first. But i think that, like 2 weeks after the release, there will be accurate descriptions for them, too :)
