### ISSUE TITLE
Vurp! reminder is not updated by Placebo Use.

### ISSUE THREAD

**Issue by Prezombie** [wofsauge/External-Item-Descriptions#560]
Vurp's description has a tooltip showing what pill was last used, but using Placebo on an active pill also updates the vurp result.

**Comment by Buurazu** [comment]
Thank you for your report. In testing, I found that Temperance? also updates Vurp in-game but not on our description. This was because we weren't adding pills used with certain flags (like mimic/no announcer) or used without a pill in our hand to our pickup history, for Echo Chamber's sake. This was also affecting transformation progress for Stompy/Adult from mimiced pills.

It was a mess of testing, but I think I've fixed a lot of issues with the system overall. The only three things right now that use the pickupHistory table are Echo Chamber, Vurp, and pill transformation progress, and they all seem to be in a better state now.
