### ISSUE TITLE
Help to translate

### ISSUE THREAD

**Issue by LuanRoger** [wofsauge/External-Item-Descriptions#57]
Hey @wofsauge, I want to offer my help to translate the mod to **PT-BR**!

**Comment by wofsauge** [comment]
Hey. Thank you very much for the offer!

Right now, we already have a Portuguese translation of the mod. How would a PT-BR translation differ from it?

Or are you interested in expanding the existing translation? For example, right now its missing translated item names and i will propably need help when repentence items need to be translated.

**Comment by LuanRoger** [comment]
Yes, there is already a Portuguese translation, but it is Portuguese from Portugal, that there are different accents and words that have a different meaning, which can make the information of some items confusing.
I can create a translation for AB+ based on the existing Portuguese translation, just correcting words.
And I would be happy to help translate Repetence

**Comment by wofsauge** [comment]
very interesting to know that there is such a difference between the two Portuguese versions. It makes sense that there should be another Portuguese translation then :)

If you want, you can start right off with translating!

The things you need to do on your side is:
1. create a new translation file (copy / paste the portuguese one)
2. rename it to "pt_br.lua"
3. inside the file: Change any occurences of `EID.descriptions["pt"]` into `EID.descriptions["pt_br"]`
4. Inside the main.lua file: add "pt_br" to the `EID.Languages` array in line 4
5. change the config.lua file to have the pt_br language active, so you can test it well :)

then its all good to go with coding / translating and testing :)

And please make sure to make backups of your progress and not working inside the folder of the original mod, since any update to a mod will completely wipe any changes made in the folder.

**Comment by LuanRoger** [comment]
Thanks! as soon as I finish I will make a pull request and close this issue.
