### ISSUE TITLE
RGON: Fix bag of crafting with modded items

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/External-Item-Descriptions#629]

**Comment by wofsauge** [comment]
repentogon fix added and tested. seems to work fine for now

**Comment by marco3102** [comment]
![image](https://github.com/wofsauge/External-Item-Descriptions/assets/116598674/aab2d915-37ef-46f9-a636-689f6f47c298)

You sure?

**Comment by marco3102** [comment]
I do.
I restarted my game. Not having the issue right now. 
Might come back. IDK
Didnt really change any mods.

**Comment by Buurazu** [comment]
It's quite possible that it was a bag content desync like usual; the way we check for swiping items can also be replaced with repentogon features but hasn't yet, I'll work on that
If it happens again please make sure that what the mod thinks is in the bag matches your real item bag
Also, I wonder if you have any mods that overwrite the base game item's qualities, right now it only checks new item IDs for their quality but it shouldn't be too slow to just check all items, I think I'll change the code to check from ID 0

**Comment by marco3102** [comment]
Repentogon sure has a lot of potential.
Ok.
I dont think that I have anything that changes quality. Might be wrong. I have alot.

**Comment by marco3102** [comment]
![image](https://github.com/wofsauge/External-Item-Descriptions/assets/116598674/ae47b17c-8e8b-4020-b369-38f680fd2f94)

You said I had to make sure it matches.
What now?

**Comment by Buurazu** [comment]
The recipe list display would show what it thinks is inside the bag

**Comment by marco3102** [comment]
Ah shit you mean the  recipie items. Ill report back 1 sec

**Comment by marco3102** [comment]
![image](https://github.com/wofsauge/External-Item-Descriptions/assets/116598674/91da18e7-7de1-4efc-86fc-59f5052dfc6c)

Sadly the Item Recipe Components appear to match

**Comment by Buurazu** [comment]
oh no, I can't think of what the issue could be then
can you join wofsauge's discord and I'll test things with you? https://discord.gg/MTZYUaqR

**Comment by marco3102** [comment]
I have considerable cut my mod collection.
Im talking from 160 -> 38.
Issue still persists.
![image](https://github.com/wofsauge/External-Item-Descriptions/assets/116598674/2a3eaa4b-139d-481d-9436-372c32d1e591)
Here are the Mods.
https://drive.google.com/file/d/1ph-Ul89s-l31_sVaUL4sKpQ2t3Ek8Rtb/view?usp=sharing

I disabled Revelations, Repentence Plus and Fiend Folio. Issue still persists.

I know you already did some testing and could narrow it down to be something with andromeda or possibly epiphany.
But I wanted to provide a shorter list of mods.
Storage Size the .rar is stll 75% as large as the old one. But only around 15% of amount of mods.

**Comment by Buurazu** [comment]
I've done a lot of testing on this and couldn't find anything conclusive on why this is happening, unfortunately...

Crafting is fairly simple behind the scenes; your bag ingredients decide what quality of items the recipe could possibly make, and then it checks the item pools you can craft from (treasure/boss/shop by default, other pools added depending on what ingredients you have), adding all the item weights together. Then it rolls a random number to determine the result. EID is sometimes saying your recipes are one item ID off from what they should be, so there's something small about this process that's not quite right.

None of the items added to the Treasure/Boss/Shop item pools in Andromeda or Epiphany seem to be doing anything strange that would mess up our crafting simulation code. Maybe there's something that our code isn't accounting for when it comes to what the base game does with modded items, or the criteria for an item being craftable at all, especially since the recent-ish updates to crafting legality when they enabled it for Tainted Lost. We might need the knowledge of someone that's reverse engineered the BoC. Alternatively, Repentogon could maybe add a function for calculating what the result of a given bag of ingredients would be. I don't know how feasible that is.

One funny thing is that, after the update that added a Crafting Quality attribute to items, all modded items are treated as Crafting Quality 0 unless they specify one. So the recipes are only inaccurate for very poor quality bags. Also, I've updated EID to use Repentogon to poll the game for what the result of a full bag will be, so even if the recipe list might be occasionally incorrect, you can at least get a description for what's in your full bag if needed.

**Comment by marco3102** [comment]
Very Interesting for sure.
I started writing here about a week ago.
Since then ive disabled  Andromeda and Epiphany for the forseeable future. Too High of a passive Post_render/Post_Process MS Drain.
Thank the Heavens and [Mod Profiler](https://steamcommunity.com/sharedfiles/filedetails/?id=2505060515) for letting me know.
Either that or your Changes fixed it.
Nice to see more Repentogon use.

**Comment by wofsauge** [comment]
The problem should be fixed now with the latest update.
