### ISSUE TITLE
Item Reminder: Make gulped trinkets scrollable in the "held trinkets" tab

### ISSUE THREAD

**Issue by wofsauge** [wofsauge/External-Item-Descriptions#691]
Gulped trinkets should be viewable in the item reminder, by using the scroll feature in the Held Trinkets tab.

Requested by oilyspoily

**Comment by Buurazu** [comment]
Got a basic version working that just reads for all trinkets; annoyingly, gulped trinkets don't count as "real" trinkets so there doesn't seem to be a good way to differentiate gulped trinkets from granted effects (e.g. rainbow worm)
Will need to actually watch for gulps; from a test with Marbles, it might be really easy because Marbles "uses" Smelter behind the scenes. The Gulp pill hopefully does the same. So just watch for Smelter being used.

**Comment by Buurazu** [comment]
Yeah, it was easy since all methods of gulping trinkets can be tracked by watching for Smelter getting used.
