### ISSUE TITLE
A notice about the rep+ installation guide screenshots.

### ISSUE THREAD

**Issue by norpba** [wofsauge/External-Item-Descriptions#762]
Hi, 

Just wanted you to know, that you can see the windows username on the second picture, even though someone (probably you) blurred the PC username in the address bar.

**Comment by wofsauge** [comment]
Thanks to the report. do you mean the right part of the screenshot on the "rep+ installation" tutorial page? because i cant find a username there that isnt blurred. can you elaborate where you see it?
(The text "Dieser P..." in the sidebar in the righ part of the screenshot is german for "This PC", if that is what you mean)
