### ISSUE TITLE
Repentance+ desync on unidentified pills/cards

### ISSUE THREAD

**Issue by nyliya** [wofsauge/External-Item-Descriptions#769]
I'm using the mod as a script so that it works with online lobbies added with Repentance+ (no mods allowed) however every time there is an unidentified pill or card I get a desync error and the person I'm playing with gets disconnected from the lobby. This happens regardless if it's just me using the script or both of us. 

Version 4.6369 works without desync but I wanted to use the updated descriptions.

I attached the files I am using in the script folder, I just edited the paths in main.lua and some of the features files from the steam workshop download.

[eidonline.zip](https://github.com/user-attachments/files/17910068/eidonline.zip)

**Comment by wofsauge** [comment]
The online version of EID is no longer supported by us and we will not provide an official version for online coop in the foreseeable future. The game explicitly disallows mods in online coop and was coded to only work well in normal, unaltered gameplay scenarios. Therefore, we will respect the decision of the game devs and not provide a guide or mod-files that are designed to work in online coop. Additionally we want to give the game devs time to fix bigger issues with the game, before they have to deal with modding support for coop.

Anyways, since you already seem to know how to make it work, you can try to set the variable `EID.isOnlineMultiplayer` to true (main.lua line 25). this deactivates all features that caused desyncs back in the alpha. Any further issues you might encounter are your problem to deal with, since i am not willing to provide help that might open unnecessary flood gates.

**Comment by xADDBx** [comment]
I've now finished multiple runs over multiple days with EID.

First I used the workaround that was used in the beta, later I just patched out the game's mod check when accessing the multiplayer menu.

With `EID.isOnlineMultiplayer` set to true, I haven't experienced any desyncs. While I understand the perspective of the Maintainer to not provide support for things that aren't even officially implemented/allowed, I just wanted to share my experience for those who want to try it themselves.

**Comment by janderjann** [comment]
> > > I've now finished multiple runs over multiple days with EID.
> > > First I used the workaround that was used in the beta, later I just patched out the game's mod check when accessing the multiplayer menu.
> > > With `EID.isOnlineMultiplayer` set to true, I haven't experienced any desyncs. While I understand the perspective of the Maintainer to not provide support for things that aren't even officially implemented/allowed, I just wanted to share my experience for those who want to try it themselves.
> > > I'd also like to thank the dev(s) for having implemented `isOnlineMultiplayer` in the past.
> > 
> > 
> > Hey man, could you please tell me how to disable the mod check you are talking about? cant find anything online
> 
> I basically just `NOP`ed out three checks (see https://github.com/xADDBx/Isaac-Online-Modded/blob/master/IsaacOnlineModded/GamePatcher.cs#L60). Though further questions on that topic should probably go on the repo I link considering this seems somewhat off-topic and the issue here is already closed.

at first thank you for replying, im almost a complete noob when it comes to anything about this, could
